react_native_path = '../node_modules/react-native'
# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Memories' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  #use_frameworks!
   source 'https://github.com/CocoaPods/Specs.git'
pod 'React', :path => react_native_path, :subspecs => [
    'Core',
    'RCTText',
    'RCTNetwork',
    'RCTImage',
    'RCTAnimation',
    'RCTWebSocket',
    'ART',
    'BatchedBridge',
    'DevSupport'
]



pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'
pod 'CodePush', :path => '../node_modules/react-native-code-push'
pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk/ios'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'
pod 'RSKImageCropper'
pod 'QBImagePickerController'
pod 'GooglePlaces'
pod 'GoogleMaps'
pod 'GooglePlacePicker'
pod 'Fabric'
pod 'Crashlytics'
end

